### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NicoGonzalez94** [josema-P020/MovieLifeplus#19]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar el logo en cada sección de la pagina

## Resultado actual

• El logo solo se encuentra en la pagina principal (Inicio) y Registrarse.

## Captura

![image](https://github.com/user-attachments/assets/29d99fe5-94b5-4f85-8a51-9cbd395842a5)
![image](https://github.com/user-attachments/assets/ff116307-4263-4ea7-9307-d32dec399c06)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by josema-P020** [comment]
logo agregado a las paginas que faltaba
