### ISSUE TITLE
Logo navbar y footer

### ISSUE THREAD

**Issue by NicoGonzalez94** [josema-P020/MovieLifeplus#20]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que al hacer click en el logo ubicado en el navbar o footer, este me redirija a la pagina principal (Inicio).

## Resultado actual

• Al hacer click en el logo este no redirige a ningún sitio. 

## Captura

![image](https://github.com/user-attachments/assets/850f0227-cabd-48c3-87b7-5468eb46ceb5)
![image](https://github.com/user-attachments/assets/21121b75-d9e7-49f2-825d-477d1cf65001)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by josema-P020** [comment]
los link fueron agregado al logo del navbar y footer
